### ISSUE TITLE
unclear how to turn off various toolbar features

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#109]
It's a bit unclear how to turn off visibility of different components and what each component / tool-set contains.   Setting all items under `visible` to `false` did not change the actual app display.  For example, the toolbar remained visible when reloaded in the notebook.  To turn off the display of at least the import data button, I needed to comment out the `g-data-tools` altogether from the toolbar, but I wasn't sure what else I was removing by doing so.  
```
settings:
  configuration: mastviz
  visible:
    menu_bar: false
    toolbar: false
    tray: false
    tab_headers: false
toolbar:
  # - g-data-tools
  - g-subset-tools
  - g-gaussian-smooth
```

Can I turn off features programmatically?  I tried the following but it didn't work.  
```
app = Application(configuration='mastviz', tray=False, toolbar=False)
```
